version: '3'

services:
  mongo:
    image: mongo:5.0.1-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - mongo
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - mongo
networks:
  mongo:
